// PixelLens — "Copy for LLM" bundle builder
//
// Fusionne, en UN SEUL document Markdown auto-descriptif, tout ce dont une IA a besoin
// pour comprendre une page : (1) son contenu converti en Markdown, (2) le design system
// extrait au dernier scan (couleurs / typo / spacing / shadows / radius) et (3) les
// métadonnées de la page. Le résultat est pensé pour être collé directement dans le
// contexte d'un assistant (Claude & co.).
//
// Fonction PURE et déterministe (aucun accès DOM / horloge / locale) → testable.

import type { MarkdownResult } from '@/types/markdown'
import type { DesignSystem } from '@/types/design-system'

export interface LlmBundleInput {
  /** Résultat de conversion de la page courante (frontmatter + corps + stats). */
  markdown: MarkdownResult
  /** Design system du dernier scan, si disponible (sinon section remplacée par une note). */
  designSystem?: DesignSystem | null
}

/**
 * Construit le document « Copy for LLM » à partir de la page convertie et, si présent,
 * du design system. Retourne une string Markdown prête à copier.
 */
export function buildLlmBundle({ markdown, designSystem }: LlmBundleInput): string {
  const { frontmatter: fm } = markdown
  const hasDs = !!designSystem

  const sections: string[] = [
    renderFrontmatter(fm, hasDs),
    `# ${escapeInline(fm.title || 'Untitled')}`,
    '> Single-file snapshot generated by PixelLens so an AI can understand this page end to' +
      ' end: its content as Markdown, the extracted design system, and page metadata.',
    '## Page content',
    markdown.markdown.trim() || '_(empty document)_',
    hasDs ? renderDesignSystem(designSystem!) : renderNoDesignSystem(),
    renderMetadata(markdown),
  ]

  return sections.join('\n\n') + '\n'
}

// --- Frontmatter global du bundle ----------------------------------------------------

function renderFrontmatter(fm: MarkdownResult['frontmatter'], hasDs: boolean): string {
  const lines = [
    'generator: PixelLens',
    'kind: llm-bundle',
    `title: ${yamlString(fm.title || 'Untitled')}`,
    `url: ${yamlString(fm.url)}`,
    `capturedAt: ${yamlString(fm.capturedAt)}`,
    `designSystem: ${hasDs ? 'included' : 'none'}`,
    `wordCount: ${fm.wordCount}`,
  ]
  return `---\n${lines.join('\n')}\n---`
}

// --- Design system -------------------------------------------------------------------

function renderNoDesignSystem(): string {
  return ['## Design system', '_No scan yet — run Scan for design tokens._'].join('\n\n')
}

function renderDesignSystem(ds: DesignSystem): string {
  const parts: string[] = [
    '## Design system',
    `_Extracted from ${escapeInline(ds.metadata.url)} · scanned ${escapeInline(
      ds.metadata.scannedAt,
    )}._`,
  ]

  if (ds.colors.length) {
    parts.push(
      '### Colors',
      table(
        ['Name', 'Hex', 'Category', 'Freq'],
        ds.colors.map((c) => [
          escapeCell(c.name),
          `\`${escapeCell(c.hex)}\``,
          escapeCell(c.category),
          String(c.frequency),
        ]),
      ),
    )
  }

  if (ds.typography.length) {
    const items = ds.typography.map((t) => {
      const variants = t.variants.map((v) => {
        const facets = [
          v.fontSize,
          v.fontWeight && `weight ${v.fontWeight}`,
          v.lineHeight && `line-height ${v.lineHeight}`,
          v.letterSpacing && `letter-spacing ${v.letterSpacing}`,
        ]
          .filter(Boolean)
          .join(' · ')
        return `  - ${escapeInline(facets) || '_(no metrics)_'}`
      })
      return [`- **${escapeInline(t.fontFamily)}**`, ...variants].join('\n')
    })
    parts.push('### Typography', items.join('\n'))
  }

  if (ds.spacing.length) {
    parts.push(
      '### Spacing',
      table(
        ['Label', 'Value', 'Freq'],
        ds.spacing.map((s) => [escapeCell(s.label), escapeCell(s.value), String(s.frequency)]),
      ),
    )
  }

  if (ds.shadows.length) {
    parts.push('### Shadows', ds.shadows.map((s) => `- \`${escapeCell(s.value)}\``).join('\n'))
  }

  if (ds.borderRadius.length) {
    parts.push(
      '### Border radius',
      table(
        ['Value', 'Freq'],
        ds.borderRadius.map((r) => [escapeCell(r.value), String(r.frequency)]),
      ),
    )
  }

  return parts.join('\n\n')
}

// --- Metadata ------------------------------------------------------------------------

function renderMetadata(markdown: MarkdownResult): string {
  const { frontmatter: fm, stats } = markdown
  const rows: [string, string][] = [
    ['Title', fm.title || 'Untitled'],
    ['URL', fm.url],
  ]
  if (fm.siteName) rows.push(['Site', fm.siteName])
  if (fm.lang) rows.push(['Language', fm.lang])
  if (fm.description) rows.push(['Description', fm.description])
  rows.push(
    ['Captured', fm.capturedAt],
    ['Words', String(fm.wordCount)],
    ['Headings', String(stats.headings)],
    ['Links', String(stats.links)],
    ['Images', String(stats.images)],
    ['Tables', String(stats.tables)],
    ['Code blocks', String(stats.codeBlocks)],
  )

  return [
    '## Metadata',
    table(
      ['Field', 'Value'],
      rows.map(([k, v]) => [escapeCell(k), escapeCell(v)]),
    ),
  ].join('\n\n')
}

// --- Helpers -------------------------------------------------------------------------

/** Rend un tableau GFM (en-tête + séparateur + lignes). */
function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`
  const sep = `| ${headers.map(() => '---').join(' | ')} |`
  const body = rows.map((cells) => `| ${cells.join(' | ')} |`)
  return [head, sep, ...body].join('\n')
}

/** Échappe un scalaire YAML entre guillemets doubles (\, " et sauts de ligne aplatis). */
function yamlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/[\r\n]+/g, ' ')
    .trim()
  return `"${escaped}"`
}

/** Aplatit les sauts de ligne d'un texte inline (titres, notes). */
function escapeInline(value: string): string {
  return value.replace(/[\r\n]+/g, ' ').trim()
}

/** Rend une valeur sûre pour une cellule de tableau GFM (pipes échappés, une seule ligne). */
function escapeCell(value: string): string {
  return value
    .replace(/\|/g, '\\|')
    .replace(/[\r\n]+/g, ' ')
    .trim()
}
